# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     rdiscount
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#站点基础配置
# title: Sauchye's Blog
subTitle: Sauchye's Blog | Just record my life
description: 
url: http://sauchye.github.io
feed: /atom.xml

#菜单配置
nav:
  - text: Home
    url: /index.html
  - text: Archives
    url: /archives.html
  - text: About
    url: /about.html


#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
 
  - class: fa-github
    url: http://github.com/sauchye
  - class: fa-weibo
    url: http://weibo.com/315526661
  - class: fa-twitter
    url: http://twitter.com/sauchye
  - class: fa-rss
    url: http://sauchye.com/atom.xml

#作者信息
# author:
#   link: http://www.zhanxin.info/contact.html
#   img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: sauchye

duoshuo:
  config: false
  id: isau